config/routes.rb
HeartRateVisualizationDemo::Application.routes.draw do

  get "hrm_sessions/show"
  resources :users, only: [:index, :show] do
    resources :hrm_sessions, only: [:index, :show]
  end

  root to: "users#index"

  

end

app/models/hrm_data_point.rb
class HrmDataPoint < ActiveRecord::Base
  belongs_to :hrm_session
end

app/models/hrm_session.rb
class HrmSession < ActiveRecord::Base
  belongs_to :user
  has_many :hrm_data_points, -> { order(:started_at) }

  before_save :set_computed_attributes

  def set_computed_attributes
    set_bpm_max
    set_bpm_min
    set_bpm_weighted_avg
    set_hr_zone1_duration
    set_hr_zone2_duration
    set_hr_zone3_duration
    set_hr_zone4_duration
  end

  def set_bpm_max
    self.bpm_max           = self.hrm_data_points.maximum(:bpm)
  end

  def set_bpm_min
    self.bpm_min           = self.hrm_data_points.minimum(:bpm)
  end

  def set_bpm_weighted_avg
    self.bpm_weighted_avg = self.hrm_data_points.to_a.sum { |e| e.bpm * e.duration } / self.hrm_data_points.sum(:duration)
  end

  def set_hr_zone1_duration
    self.hr_zone1_duration = set_hr_zone_duration(self.user.hr_zone1_bpm_min, self.user.hr_zone1_bpm_max)
  end

  def set_hr_zone2_duration
    self.hr_zone2_duration = set_hr_zone_duration(self.user.hr_zone2_bpm_min, self.user.hr_zone2_bpm_max)
  end

  def set_hr_zone3_duration
    self.hr_zone3_duration = set_hr_zone_duration(self.user.hr_zone3_bpm_min, self.user.hr_zone3_bpm_max)
  end

  def set_hr_zone4_duration
    self.hr_zone4_duration = set_hr_zone_duration(self.user.hr_zone4_bpm_min, self.user.hr_zone4_bpm_max)
  end

  private

  def set_hr_zone_duration(min, max)
    self.hrm_data_points.where("bpm >= ? and bpm <= ?", min, max).sum(:duration)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :hrm_sessions, -> { order("created_at desc") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hrm_sessions_controller.rb
class HrmSessionsController < ApplicationController

  before_action :set_user

  def index
    @hrm_sessions = @user.hrm_sessions
  end

  def show
    @hrm_session = @user.hrm_sessions.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:id).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def seconds_to_human_time(seconds)
    mm, ss = seconds.divmod(60)
    "%02d:%02d" % [mm, ss]     # todo: support hours
  end
end

app/helpers/hrm_sessions_helper.rb
module HrmSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hrm_sessions/index.html.erb
<div class="page-header">

  <ul class="breadcrumb">
    <li><%= link_to "Users", users_path %> <span class="divider">/</span></li>
    <li><%= link_to "User", user_path(@user) %> <span class="divider">/</span></li>
    <li class="active">Sessions</li>
  </ul>

  <h1>Sessions for <%= @user.username %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Min</th>
      <th>Max</th>
      <th>Avg</th>
      <th>Zone 1</th>
      <th>Zone 2</th>
      <th>Zone 3</th>
      <th>Zone 4</th>
      <th>Total duration</th>
    </tr>
  </thead>

  <tbody>
    <% @hrm_sessions.each do |hrm_session| %>
      <tr>
        <td><%= link_to l(hrm_session.created_at, format: :long), [@user, hrm_session] %></td>
        <td><%= hrm_session.bpm_min if hrm_session.bpm_min %></td>
        <td><%= hrm_session.bpm_max if hrm_session.bpm_max %></td>
        <td><%= hrm_session.bpm_weighted_avg if hrm_session.bpm_weighted_avg %></td>
        <td><%= seconds_to_human_time hrm_session.hr_zone1_duration if hrm_session.hr_zone1_duration %></td>
        <td><%= seconds_to_human_time hrm_session.hr_zone2_duration if hrm_session.hr_zone2_duration %></td>
        <td><%= seconds_to_human_time hrm_session.hr_zone3_duration if hrm_session.hr_zone3_duration %></td>
        <td><%= seconds_to_human_time hrm_session.hr_zone4_duration if hrm_session.hr_zone4_duration %></td>
        <td><%= seconds_to_human_time hrm_session.duration %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hrm_sessions/show.html.erb
<div class="page-header">

  <ul class="breadcrumb">
    <li><%= link_to "Users", users_path %> <span class="divider">/</span></li>
    <li><%= link_to "User", user_path(@user) %> <span class="divider">/</span></li>
    <li><%= link_to "Sessions", user_hrm_sessions_path(@user) %> <span class="divider">/</span></li>
    <li class="active">Session</li>
  </ul>

  <h1>Session for <%= @user.username %></h1>
  <h3><%= l @hrm_session.created_at, format: :long %></h3>
  <h5><%= seconds_to_human_time @hrm_session.duration %></h5>
</div>

<%= content_tag "div", id: "hrm-data-points-chart", class: "chart-container", data: {hrm_data_points: @hrm_session.hrm_data_points.inject([]){|memo, x| memo << [x.started_at, x.bpm] ; memo} } do %>
  Loading...
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Heart Rate Visualization Demo</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
 </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Heart Rate Visualization Demo</a>
        </div>
      </div>
    </div>

    <div class="container-fluid container-narrow">
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/index.html.erb
<div class="page-header">

  <ul class="breadcrumb">
    <li class="active">Users</li>
  </ul>

  <h1>Users</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Created at</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.gender %></td>
        <td><%= user.age %></td>
        <td><%= l user.created_at, format: :short %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/users/show.html.erb
<div class="page-header">

  <ul class="breadcrumb">
    <li><%= link_to "Users", users_path %> <span class="divider">/</span></li>
    <li class="active">User</li>
  </ul>

  <h1><%= @user.username %></h1>
</div>
<div class="well">
  <%= link_to "View Sessions", user_hrm_sessions_path(@user), class: "btn" %>
</div>


<table class="table table-bordered">
  <tbody>
    <tr><td>Username</td>                 <td><%= @user.username %></td></tr>
    <tr><td>Gender</td>                   <td><%= @user.gender %></td></tr>
    <tr><td>Age</td>                      <td><%= @user.age %></td></tr>
    <tr><td>Created At</td>               <td><%= l @user.created_at, format: :long %></td></tr>
    <tr><td>HR Zone1 BPM Min</td>         <td><%= @user.hr_zone1_bpm_min %></td></tr>
    <tr><td>HR Zone1 BPM Max</td>         <td><%= @user.hr_zone1_bpm_max %></td></tr>
    <tr><td>HR Zone2 BPM Min</td>         <td><%= @user.hr_zone2_bpm_min %></td></tr>
    <tr><td>HR Zone2 BPM Max</td>         <td><%= @user.hr_zone2_bpm_max %></td></tr>
    <tr><td>HR Zone3 BPM Min</td>         <td><%= @user.hr_zone3_bpm_min %></td></tr>
    <tr><td>HR Zone3 BPM Max</td>         <td><%= @user.hr_zone3_bpm_max %></td></tr>
    <tr><td>HR Zone4 BPM Min</td>         <td><%= @user.hr_zone4_bpm_min %></td></tr>
    <tr><td>HR Zone4 BPM Max</td>         <td><%= @user.hr_zone4_bpm_max %></td></tr>
  </tbody>
</table>